name: Trading Bot Workflow

on:
  schedule:
    - cron: "0 * * * *"  # Jalankan setiap 4 jam
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Trading Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python TradingView.py

  commit-changes:
    needs: run-bot
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'chore: Auto-update active buys data'
        file_pattern: active_buys.json
        commit_user_name: Trading Bot
        commit_user_email: bot@trading.com
        branch: main
